// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spendnest.Infrastructure.Persistence;

#nullable disable

namespace Spendnest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpendnestDbContext))]
    partial class SpendnestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Spendnest.Core.Accounts.CardAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardAccounts", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Categorization.CategoryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryRules", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Categorization.TransactionCategoryAssignment", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NeedsReview");

                    b.ToTable("TransactionCategoryAssignments", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Importing.StatementImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParsedRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SavedTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedDuplicateTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardAccountId");

                    b.HasIndex("FileHash");

                    b.ToTable("StatementImports", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StatementImportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardAccountId");

                    b.HasIndex("PostedDate");

                    b.HasIndex("StatementImportId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Spendnest.Core.Categorization.CategoryRule", b =>
                {
                    b.HasOne("Spendnest.Core.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Spendnest.Core.Categorization.TransactionCategoryAssignment", b =>
                {
                    b.HasOne("Spendnest.Core.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spendnest.Core.Transactions.Transaction", null)
                        .WithOne()
                        .HasForeignKey("Spendnest.Core.Categorization.TransactionCategoryAssignment", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spendnest.Core.Importing.StatementImport", b =>
                {
                    b.HasOne("Spendnest.Core.Accounts.CardAccount", null)
                        .WithMany()
                        .HasForeignKey("CardAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Spendnest.Core.Transactions.Transaction", b =>
                {
                    b.HasOne("Spendnest.Core.Accounts.CardAccount", null)
                        .WithMany()
                        .HasForeignKey("CardAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spendnest.Core.Importing.StatementImport", null)
                        .WithMany()
                        .HasForeignKey("StatementImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
